// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class PlayConstantNames
{
        public const string achievement_week_3_completed = "CgkIsqTI3JUKEAIQAw"; // <GPGSID>
        public const string achievement_week_1_perfected = "CgkIsqTI3JUKEAIQBw"; // <GPGSID>
        public const string leaderboard_star_count = "CgkIsqTI3JUKEAIQDw"; // <GPGSID>
        public const string achievement_week_2_perfected = "CgkIsqTI3JUKEAIQCA"; // <GPGSID>
        public const string achievement_week_5_perfected = "CgkIsqTI3JUKEAIQCw"; // <GPGSID>
        public const string achievement_week_1_completed = "CgkIsqTI3JUKEAIQAQ"; // <GPGSID>
        public const string achievement_week_2_completed = "CgkIsqTI3JUKEAIQAg"; // <GPGSID>
        public const string achievement_week_4_perfected = "CgkIsqTI3JUKEAIQCg"; // <GPGSID>
        public const string achievement_week_5_completed = "CgkIsqTI3JUKEAIQBQ"; // <GPGSID>
        public const string achievement_all_sessions_completed = "CgkIsqTI3JUKEAIQDQ"; // <GPGSID>
        public const string achievement_week_4_completed = "CgkIsqTI3JUKEAIQBA"; // <GPGSID>
        public const string achievement_week_6_perfected = "CgkIsqTI3JUKEAIQDA"; // <GPGSID>
        public const string achievement_week_3_perfected = "CgkIsqTI3JUKEAIQCQ"; // <GPGSID>
        public const string achievement_all_sessions_perfected = "CgkIsqTI3JUKEAIQDg"; // <GPGSID>
        public const string achievement_week_6_completed = "CgkIsqTI3JUKEAIQBg"; // <GPGSID>

}

